-- CIRUJANO DB - Componentes desde Excel
-- Generado: 2026-01-05 22:10:02

INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (16000.0, '16kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (16200.0, '16kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3.9, '3.9Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (8.2, '8.2Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (0.33, '0.33Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (7870.0, '7.9kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3000000.0, '3MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (0.5, '0.5Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1.0, '1Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (0.6, '0.6Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1.2, '1.2Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1.3, '1.3Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1.5, '1.5Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1.8, '1.8Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (2.0, '2Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (2.2, '2.2Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (130000.0, '1.3e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (2.4, '2.4Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (2.7, '2.7Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3.0, '3Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (160000.0, '1.6e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3.3, '3.3Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1000000.0, '1MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3000.0, '3kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (2400.0, '2.4kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (7500.0, '7.5kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (825.0, '8.2e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1200.0, '1.2kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (15.0, '15Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3.6, '3.6Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (4.3, '4.3Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (2700.0, '2.7kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (4.7, '4.7Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (330000.0, '3.3e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (510000.0, '5.1e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (910.0, '9.1e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (240000.0, '2.4e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1000.0, '1kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1100.0, '1.1kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1500.0, '1.5kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (200000.0, '2e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (43000.0, '43kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1600.0, '1.6kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1800.0, '1.8kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (2000.0, '2kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3300.0, '3.3kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (680.0, '6.8e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (2200.0, '2.2kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (5.1, '5.1Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (6.8, '6.8Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (6.2, '6.2Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (7.5, '7.5Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (9.1, '9.1Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (10.0, '10Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (5.6, '5.6Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (11.0, '11Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (12.0, '12Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (18.0, '18Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (20.0, '20Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (21.0, '21Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (22.0, '22Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (24.0, '24Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (845.0, '8.4e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (27.0, '27Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (30.0, '30Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (33.0, '33Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (36.0, '36Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (39.0, '39Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (43.0, '43Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (47.0, '47Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (68100.0, '68kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (820.0, '8.2e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (34600.0, '35kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (180000.0, '1.8e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (51.0, '51Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (36000.0, '36kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (360000.0, '3.6e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (27000.0, '27kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (68.0, '68Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (75.0, '75Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (82.0, '82Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (100.0, '1e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (91.0, '91Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (13000.0, '13kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (100000.0, '1e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (6800.0, '6.8kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (750000.0, '7.5e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (12000.0, '12kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (15000.0, '15kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (11000.0, '11kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (10000.0, '10kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (6200.0, '6.2kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (4900.0, '4.9kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (9100.0, '9.1kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (53000.0, '53kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3600.0, '3.6kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (5100.0, '5.1kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3900.0, '3.9kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (8200.0, '8.2kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (4300.0, '4.3kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (4700.0, '4.7kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (5600.0, '5.6kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (820000.0, '8.2e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (240.0, '2.4e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (220000.0, '2.2e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (300000.0, '3e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (130.0, '1.3e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (56.0, '56Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (200.0, '2e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (91000.0, '91kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (18000.0, '18kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (20000.0, '20kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (110.0, '1.1e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (82000.0, '82kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (120.0, '1.2e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (390.0, '3.9e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (430.0, '4.3e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (150.0, '1.5e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (160.0, '1.6e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (180.0, '1.8e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (220.0, '2.2e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (620000.0, '6.2e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (47000.0, '47kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (300.0, '3e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (270.0, '2.7e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (2200000.0, '2.2MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (910000.0, '9.1e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (360.0, '3.6e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (68000.0, '68kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (390000.0, '3.9e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (620.0, '6.2e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (120000.0, '1.2e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (62.0, '62Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (51000.0, '51kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (30000.0, '30kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1500000.0, '1.5MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (430000.0, '4.3e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (330.0, '3.3e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (127000.0, '1.3e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (150000.0, '1.5e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (470.0, '4.7e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (510.0, '5.1e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (750.0, '7.5e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (560.0, '5.6e+02Ω', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (22000.0, '22kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1200000.0, '1.2MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (24000.0, '24kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (110000.0, '1.1e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (560000.0, '5.6e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (75000.0, '75kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (680000.0, '6.8e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (2400000.0, '2.4MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (39000.0, '39kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (33000.0, '33kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (63400.0, '63kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (56000.0, '56kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (470000.0, '4.7e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (62000.0, '62kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (1800000.0, '1.8MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (270000.0, '2.7e+02kΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3300000.0, '3.3MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (3900000.0, '3.9MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (4700000.0, '4.7MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (5100000.0, '5.1MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (5600000.0, '5.6MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (6800000.0, '6.8MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (8200000.0, '8.2MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_resistors (value_ohms, display_value, tolerance_percent, power_watts, technology, package) VALUES (10000000.0, '10MΩ', 5.0, 0.25, 'METAL_FILM', 'TH_AXIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (3.9999999999999996e-05, '40µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.0003, '3e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (1e-06, '1µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (2e-06, '2µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (4e-06, '4µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (3e-06, '3µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (4.9999999999999996e-06, '5µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (6e-06, '6µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (7e-06, '7µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (8e-06, '8µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (9e-06, '9µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (9.999999999999999e-06, '10µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (1.8e-05, '18µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (1.9999999999999998e-05, '20µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (2.7e-05, '27µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (2.9999999999999997e-05, '30µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000385, '3.8e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000683, '6.8e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00015099999999999998, '1.5e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (3.2999999999999996e-05, '33µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (4.9999999999999996e-05, '50µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (5.6e-05, '56µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000473, '4.7e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000474, '4.7e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (1.4999999999999999e-05, '15µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (6.8e-05, '68µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (9.999999999999999e-05, '1e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (8.2e-05, '82µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00015, '1.5e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000101, '1e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000121, '1.2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (7.5e-05, '75µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00014099999999999998, '1.4e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00021999999999999998, '2.2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00018099999999999998, '1.8e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00020099999999999998, '2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00022099999999999998, '2.2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000271, '2.7e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00033099999999999997, '3.3e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00027299999999999997, '2.7e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000561, '5.6e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000681, '6.8e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000821, '8.2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.0008219999999999999, '8.2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00015199999999999998, '1.5e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (4.7e-05, '47µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00047, '4.7e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (5.9999999999999995e-05, '60µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00047099999999999996, '4.7e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000682, '6.8e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.0006039999999999999, '6e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000153, '1.5e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000101, '1e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000154, '1.5e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (2.2e-05, '22µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000104, '1e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000562, '5.6e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000222, '2.2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000102, '1e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000103, '1e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000332, '3.3e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000472, '4.7e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00010499999999999999, '1e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000106, '1.1e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00022099999999999998, '2.2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000223, '2.2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000254, '2.5e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000224, '2.2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000202, '2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00030399999999999996, '3e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.0005639999999999999, '5.6e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000334, '3.3e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00044199999999999996, '4.4e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000203, '2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.000823, '8.2e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, package) VALUES (0.00033299999999999996, '3.3e+02µF', 'CERAMIC', 50.0, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (0.00021999999999999998, '2.2e+02µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (1e-07, '0.1µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (2.1999999999999998e-07, '0.22µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (6.800000000000001e-07, '0.68µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (4.6999999999999995e-07, '0.47µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (1e-06, '1µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (2e-06, '2µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (2.2e-06, '2.2µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (3.2999999999999997e-06, '3.3µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (4.7e-06, '4.7µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (9.999999999999999e-06, '10µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (9.999999999999999e-06, '10µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (2.2e-05, '22µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (3.2999999999999996e-05, '33µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (4.7e-05, '47µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (9.999999999999999e-05, '1e+02µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (0.001, '1e+03µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (0.0033, '3.3e+03µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric, voltage_volts, polarized, package) VALUES (0.0047, '4.7e+03µF', 'ELECTROLYTIC_AL', 25.0, 1, 'TH_RADIAL');
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('7555', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('7660', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('12320VH25V', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('12F629', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('16F628', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('16F648', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('16F684', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('16F84', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('16F877', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('16F88', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('16F886', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('16F887', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('18F4520', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('18F4550', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('24LC04', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('24LC16', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('44LS157', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('4N25', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('4N26', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('4N36', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('5218A', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('6N137', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74HC132', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74HC138', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74HC14', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74HC154', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74HC245', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74HC373', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74HC4051', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74LS04', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74LS08', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74LS14', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('74LS48', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('AC3105I', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('AK4318', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('AK4526VQ', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('AN7147N', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('ATMEGA328P', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('ATTINY2313', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('ATTINY4313', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('BA5417', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CA3046', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CA3080', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD14538', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD40106', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD40109', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4011', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4013', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4016', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4017', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4020', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4027', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4029', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4040', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4047', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4049', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4051', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4052', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4053', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4060', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4066', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4067', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4069', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4072', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4073', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4081', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4093', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4094', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CD4096', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('CPH6302', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('D41416C', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('D72064LM', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('DG412', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('FT232RL', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('FW828', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('HJ238', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('HT8950', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('JCR4556', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('JCR4558', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('JCR4560', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('JCR4565', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('JCR4580', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('KA2206', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('KA2535', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LA4227', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM051A', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM13600', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM13700', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM1496', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM1881', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM2574', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM311', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM324', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM339', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM3578AN', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM358', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM386', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM3900', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM393', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM394', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM741', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LM831N', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LNK3046N', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LT8304', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('LV125A', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('MAX1044', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('MAX232', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('MB81C4526A', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('MC1489', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('MCP4822', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('MCP6004', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('MOC3021', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('MP1470GJ', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('MX7528', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('NE5532', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('NE5534', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('NE555', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('NE556', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('NE567', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('NJM2374', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('NNC6.2MG-T1', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('OB2269CP', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('OP07', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('OPA2137PA', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('PC2581V', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('PCA9532', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('PT2399', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('RN5RG33AA', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('RRL025P03TR', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('SM76489AN', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('SN74173', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('SN7517', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('SN75240W', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('SN75441', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TDA2822M', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TDA7294', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TDA9108', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TGA2025', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('THAT1646', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TL071', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TL072', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TL074', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TL082', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TL084', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TLC2272', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TLC5940', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TMS4145', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TPS54240DGQR', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TPS5430', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TPS7A3401DGNR', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TPS7A3401DGNR', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TSB41AB2', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('TUSB3200', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('UC3843', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('UL26', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('UMG9NTR (G9)', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('USB3343', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('V54C3256164VDI7', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('VA220M', 'DIP', 5.0);
INSERT INTO comp_integrated_circuits (part_number, package, voltage_volts) VALUES ('WOOA', 'DIP', 5.0);
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2SC4207-Y', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('SS13J532R', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2387A', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('20N60', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N222', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N2907', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N3904', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N4401', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N3906', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N5087', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N5088', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N5089', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N5401', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N5457', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N5458', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N5460', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N5551', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2N6111G', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2SC2060', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('MPSA18', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('MPF102', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('MUR1620R6', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM7805', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM7805', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC517', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2SK30A', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('A1015', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('MPSA13', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('A1273', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM7809', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM7812', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM7815', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM7909', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('EL817', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM7912', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM7915', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('MBR20100', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('OGBCON', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('P20N06', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('MIC29302', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('A42', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('A933', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('AZ1117', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('B1342', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('B772P', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('B824', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('B1568', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC327', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC337', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC547', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC548', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC549', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC550', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC556', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM7808', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC557', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC558', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BD138', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BD438', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BD651', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BS170', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BT136', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM35', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BT137', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2387A', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BTA16', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('C1740', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('C18158', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('C3199', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('C2655', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('TL431A', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('TOP224YN', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('TSF1060M', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BC847PN', 'BJT', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('SK3050', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('SRF2060L', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('TF8N80', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('S9013', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('PQ10621H', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('R6775', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('S9014', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('S8050', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('P20N60', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('S8550', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('S9012', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('S9015', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('J112', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('C945', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BTA10', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('IRF630', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('742669095252 (K2-2)', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('2SA1037AK (FR)', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('C3421-Y', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('C4408', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('K163', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('K246', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('D313', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('IRF1010', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('IRF4227', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('IRF634', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('J175', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('J113', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('J201', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM337', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BTA12', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('BZT52C5V6 (W9)', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LL2705', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM2576', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM2596', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM334', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('LM317', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('TSP73801DCQR', 'MOSFET', 'TO92');
INSERT INTO comp_transistors (part_number, type, package) VALUES ('IRF540NS', 'MOSFET', 'TO92');
INSERT INTO comp_diodes (part_number, type, package) VALUES ('BZT52C11 (WG)', 'RECTIFIER', 'DO41');
INSERT INTO comp_diodes (part_number, type, package) VALUES ('1SS367', 'RECTIFIER', 'DO41');
INSERT INTO comp_diodes (part_number, type, package) VALUES ('MBR0540W', 'RECTIFIER', 'DO41');