-- CIRUJANO DB - BASE DE DATOS PROFESIONAL
-- Generado: 2026-01-05 23:45:57

PRAGMA foreign_keys = ON;
PRAGMA encoding = 'UTF-8';

DROP TABLE IF EXISTS comp_resistors;
DROP TABLE IF EXISTS comp_capacitors;
DROP TABLE IF EXISTS comp_integrated_circuits;
DROP TABLE IF EXISTS comp_transistors;
DROP TABLE IF EXISTS comp_diodes;

CREATE TABLE comp_resistors (id INTEGER PRIMARY KEY, value_ohms REAL UNIQUE, display_value TEXT);
CREATE TABLE comp_capacitors (id INTEGER PRIMARY KEY, value_farads REAL, display_value TEXT, dielectric TEXT);
CREATE TABLE comp_integrated_circuits (id INTEGER PRIMARY KEY, part_number TEXT UNIQUE);
CREATE TABLE comp_transistors (id INTEGER PRIMARY KEY, part_number TEXT UNIQUE);
CREATE TABLE comp_diodes (id INTEGER PRIMARY KEY, part_number TEXT UNIQUE);

INSERT INTO comp_resistors (value_ohms, display_value) VALUES (0.33, '0.33Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (0.5, '0.5Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (0.6, '0.6Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1.0, '1Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1.2, '1.2Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1.3, '1.3Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1.5, '1.5Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1.8, '1.8Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (2.0, '2Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (2.2, '2.2Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (2.4, '2.4Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (2.7, '2.7Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3.0, '3Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3.3, '3.3Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3.6, '3.6Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3.9, '3.9Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (4.3, '4.3Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (4.7, '4.7Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (5.1, '5.1Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (5.6, '5.6Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (6.2, '6.2Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (6.8, '6.8Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (7.5, '7.5Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (8.2, '8.2Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (9.1, '9.1Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (10.0, '10Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (11.0, '11Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (12.0, '12Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (15.0, '15Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (18.0, '18Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (20.0, '20Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (21.0, '21Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (22.0, '22Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (24.0, '24Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (27.0, '27Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (30.0, '30Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (33.0, '33Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (36.0, '36Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (39.0, '39Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (43.0, '43Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (47.0, '47Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (51.0, '51Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (56.0, '56Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (62.0, '62Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (68.0, '68Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (75.0, '75Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (82.0, '82Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (91.0, '91Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (100.0, '1e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (110.0, '1.1e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (120.0, '1.2e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (130.0, '1.3e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (150.0, '1.5e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (160.0, '1.6e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (180.0, '1.8e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (200.0, '2e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (220.0, '2.2e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (240.0, '2.4e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (270.0, '2.7e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (300.0, '3e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (330.0, '3.3e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (360.0, '3.6e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (390.0, '3.9e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (430.0, '4.3e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (470.0, '4.7e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (510.0, '5.1e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (560.0, '5.6e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (620.0, '6.2e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (680.0, '6.8e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (750.0, '7.5e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (820.0, '8.2e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (825.0, '8.2e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (845.0, '8.4e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (910.0, '9.1e+02Ω');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1000.0, '1kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1100.0, '1.1kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1200.0, '1.2kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1500.0, '1.5kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1600.0, '1.6kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1800.0, '1.8kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (2000.0, '2kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (2200.0, '2.2kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (2400.0, '2.4kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (2700.0, '2.7kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3000.0, '3kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3300.0, '3.3kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3600.0, '3.6kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3900.0, '3.9kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (4300.0, '4.3kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (4700.0, '4.7kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (4900.0, '4.9kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (5100.0, '5.1kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (5600.0, '5.6kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (6200.0, '6.2kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (6800.0, '6.8kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (7500.0, '7.5kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (7870.0, '7.9kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (8200.0, '8.2kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (9100.0, '9.1kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (10000.0, '10kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (11000.0, '11kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (12000.0, '12kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (13000.0, '13kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (15000.0, '15kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (16000.0, '16kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (16200.0, '16kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (18000.0, '18kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (20000.0, '20kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (22000.0, '22kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (24000.0, '24kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (27000.0, '27kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (30000.0, '30kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (33000.0, '33kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (34600.0, '35kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (36000.0, '36kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (39000.0, '39kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (43000.0, '43kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (47000.0, '47kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (51000.0, '51kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (53000.0, '53kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (56000.0, '56kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (62000.0, '62kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (63400.0, '63kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (68000.0, '68kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (68100.0, '68kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (75000.0, '75kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (82000.0, '82kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (91000.0, '91kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (100000.0, '1e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (110000.0, '1.1e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (120000.0, '1.2e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (127000.0, '1.3e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (130000.0, '1.3e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (150000.0, '1.5e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (160000.0, '1.6e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (180000.0, '1.8e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (200000.0, '2e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (220000.0, '2.2e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (240000.0, '2.4e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (270000.0, '2.7e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (300000.0, '3e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (330000.0, '3.3e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (360000.0, '3.6e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (390000.0, '3.9e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (430000.0, '4.3e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (470000.0, '4.7e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (510000.0, '5.1e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (560000.0, '5.6e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (620000.0, '6.2e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (680000.0, '6.8e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (750000.0, '7.5e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (820000.0, '8.2e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (910000.0, '9.1e+02kΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1000000.0, '1MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1200000.0, '1.2MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1500000.0, '1.5MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (1800000.0, '1.8MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (2200000.0, '2.2MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (2400000.0, '2.4MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3000000.0, '3MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3300000.0, '3.3MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (3900000.0, '3.9MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (4700000.0, '4.7MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (5100000.0, '5.1MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (5600000.0, '5.6MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (6800000.0, '6.8MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (8200000.0, '8.2MΩ');
INSERT INTO comp_resistors (value_ohms, display_value) VALUES (10000000.0, '10MΩ');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (1e-06, '1µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (2e-06, '2µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (3e-06, '3µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (4e-06, '4µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (4.9999999999999996e-06, '5µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (6e-06, '6µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (7e-06, '7µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (8e-06, '8µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (9e-06, '9µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (9.999999999999999e-06, '10µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (1.4999999999999999e-05, '15µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (1.8e-05, '18µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (1.9999999999999998e-05, '20µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (2.2e-05, '22µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (2.7e-05, '27µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (2.9999999999999997e-05, '30µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (3.2999999999999996e-05, '33µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (3.9999999999999996e-05, '40µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (4.7e-05, '47µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (4.9999999999999996e-05, '50µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (5.6e-05, '56µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (5.9999999999999995e-05, '60µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (6.8e-05, '68µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (7.5e-05, '75µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (8.2e-05, '82µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (9.999999999999999e-05, '1e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000101, '1e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000102, '1e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000103, '1e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000104, '1e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00010499999999999999, '1e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000106, '1.1e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000121, '1.2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00014099999999999998, '1.4e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00015, '1.5e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00015099999999999998, '1.5e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00015199999999999998, '1.5e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000153, '1.5e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000154, '1.5e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00018099999999999998, '1.8e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00020099999999999998, '2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000202, '2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000203, '2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00021999999999999998, '2.2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00022099999999999998, '2.2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000222, '2.2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000223, '2.2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000224, '2.2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000254, '2.5e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000271, '2.7e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00027299999999999997, '2.7e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.0003, '3e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00030399999999999996, '3e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00033099999999999997, '3.3e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000332, '3.3e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00033299999999999996, '3.3e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000334, '3.3e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000385, '3.8e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00044199999999999996, '4.4e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00047, '4.7e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00047099999999999996, '4.7e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000472, '4.7e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000473, '4.7e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000474, '4.7e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000561, '5.6e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000562, '5.6e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.0005639999999999999, '5.6e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.0006039999999999999, '6e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000681, '6.8e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000682, '6.8e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000683, '6.8e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000821, '8.2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.0008219999999999999, '8.2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.000823, '8.2e+02µF', 'CERAMIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (1e-07, '0.1µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (2.1999999999999998e-07, '0.22µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (4.6999999999999995e-07, '0.47µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (6.800000000000001e-07, '0.68µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (1e-06, '1µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (2e-06, '2µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (2.2e-06, '2.2µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (3.2999999999999997e-06, '3.3µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (4.7e-06, '4.7µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (6.799999999999999e-06, '6.8µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (9.999999999999999e-06, '10µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (2.2e-05, '22µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (3.2999999999999996e-05, '33µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (4.7e-05, '47µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (9.999999999999999e-05, '1e+02µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.00021999999999999998, '2.2e+02µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.001, '1e+03µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.0033, '3.3e+03µF', 'ELECTROLYTIC');
INSERT INTO comp_capacitors (value_farads, display_value, dielectric) VALUES (0.0047, '4.7e+03µF', 'ELECTROLYTIC');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('7555');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('7660');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('12320VH25V');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('12F629');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('16F628');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('16F648');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('16F684');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('16F84');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('16F877');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('16F88');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('16F886');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('16F887');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('18F4520');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('18F4550');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('24LC04');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('24LC16');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('44LS157');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('4N25');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('4N26');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('4N36');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('5218A');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('6N137');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74HC04');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74HC132');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74HC138');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74HC14');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74HC154');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74HC245');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74HC373');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74HC4051');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74HC75');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74LS04');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74LS08');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74LS14');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74LS48');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('AC3105I');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('AK4318');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('AK4526VQ');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('AN7147N');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('ATMEGA328P');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('ATTINY2313');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('ATTINY4313');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('BA5417');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CA3046');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CA3080');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD14538');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD40106');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD40109');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4011');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4013');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4015');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4016');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4017');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4020');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4027');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4029');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4040');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4047');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4049');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4051');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4052');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4053');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4060');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4066');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4067');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4069');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4072');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4073');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4081');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4093');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4094');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CD4096');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('CPH6302');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('D41416C');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('D72064LM');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('DG412');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('FT232RL');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('FW828');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('HJ238');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('HT8950');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('JRC2903');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('JCR4556');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('JCR4558');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('JCR4560');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('JCR4565');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('JCR4580');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('KA2206');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('KA2535');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LA4227');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM051A');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM13600');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM13700');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM1496');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM1881');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM2574');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM311');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM324');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM339');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM3578AN');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM358');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM386');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM3900');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM393');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM394');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM741');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LM831N');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LNK3046N');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LT8304');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('LV125A');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('MAX1044');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('MAX232');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('MB81C4526A');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('MC1489');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('MCP4822');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('MCP6004');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('MOC3021');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('MP1470GJ');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('MX7528');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('NE5532');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('NE5534');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('NE555');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('NE556');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('NE567');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('NJM2374');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('NNC6.2MG-T1');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('OB2269CP');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('OP07');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('OPA2137PA');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('PC2581V');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('PCA9532');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('PT2399');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('RN5RG33AA');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('RRL025P03TR');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('SM76489AN');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('SN74157');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('SN74173');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('SN75176');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('SN75240W');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('SN754410');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TDA2822M');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TDA7294');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TDA9108');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TEA2025');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('THAT1646');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TL071');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TL072');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TL074');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TL082');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TL084');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TLC2272');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TLC5940');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TMS4145');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TPS54240DGQR');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TPS5430');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TPS7A3401DGNR');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TSB41AB2');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('TUSB3200');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('UC3843');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('UL26');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('UMG9NTR (G9)');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('USB3343');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('V54C3256164VDI7');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('VA220M');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('WOOA');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('P721F');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('UPC4570HA');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('YDA176');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('HT6116-70');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('UPD63200GS');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('23L256I');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('74HC166');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('MC14556B');
INSERT INTO comp_integrated_circuits (part_number) VALUES ('SN74LS90N');
INSERT INTO comp_transistors (part_number) VALUES ('20N60');
INSERT INTO comp_transistors (part_number) VALUES ('2387A');
INSERT INTO comp_transistors (part_number) VALUES ('2N222');
INSERT INTO comp_transistors (part_number) VALUES ('2N2907');
INSERT INTO comp_transistors (part_number) VALUES ('2N3904');
INSERT INTO comp_transistors (part_number) VALUES ('2N3906');
INSERT INTO comp_transistors (part_number) VALUES ('2N4401');
INSERT INTO comp_transistors (part_number) VALUES ('2N5087');
INSERT INTO comp_transistors (part_number) VALUES ('2N5088');
INSERT INTO comp_transistors (part_number) VALUES ('2N5089');
INSERT INTO comp_transistors (part_number) VALUES ('2N5401');
INSERT INTO comp_transistors (part_number) VALUES ('2N5457');
INSERT INTO comp_transistors (part_number) VALUES ('2N5458');
INSERT INTO comp_transistors (part_number) VALUES ('2N5460');
INSERT INTO comp_transistors (part_number) VALUES ('2N5551');
INSERT INTO comp_transistors (part_number) VALUES ('2N6111G');
INSERT INTO comp_transistors (part_number) VALUES ('2SA1037AK (FR)');
INSERT INTO comp_transistors (part_number) VALUES ('2SC2060');
INSERT INTO comp_transistors (part_number) VALUES ('2SC4207-Y');
INSERT INTO comp_transistors (part_number) VALUES ('2SK30A');
INSERT INTO comp_transistors (part_number) VALUES ('742669095252 (K2-2)');
INSERT INTO comp_transistors (part_number) VALUES ('A1015');
INSERT INTO comp_transistors (part_number) VALUES ('A1273');
INSERT INTO comp_transistors (part_number) VALUES ('A42');
INSERT INTO comp_transistors (part_number) VALUES ('A933');
INSERT INTO comp_transistors (part_number) VALUES ('AZ1117');
INSERT INTO comp_transistors (part_number) VALUES ('B1342');
INSERT INTO comp_transistors (part_number) VALUES ('B1568');
INSERT INTO comp_transistors (part_number) VALUES ('B772P');
INSERT INTO comp_transistors (part_number) VALUES ('B824');
INSERT INTO comp_transistors (part_number) VALUES ('BC327');
INSERT INTO comp_transistors (part_number) VALUES ('BC337');
INSERT INTO comp_transistors (part_number) VALUES ('BC517');
INSERT INTO comp_transistors (part_number) VALUES ('BC547');
INSERT INTO comp_transistors (part_number) VALUES ('BC548');
INSERT INTO comp_transistors (part_number) VALUES ('BC549');
INSERT INTO comp_transistors (part_number) VALUES ('BC550');
INSERT INTO comp_transistors (part_number) VALUES ('BC556');
INSERT INTO comp_transistors (part_number) VALUES ('BC557');
INSERT INTO comp_transistors (part_number) VALUES ('BC558');
INSERT INTO comp_transistors (part_number) VALUES ('BC847PN');
INSERT INTO comp_transistors (part_number) VALUES ('BD138');
INSERT INTO comp_transistors (part_number) VALUES ('BD438');
INSERT INTO comp_transistors (part_number) VALUES ('BD651');
INSERT INTO comp_transistors (part_number) VALUES ('BS170');
INSERT INTO comp_transistors (part_number) VALUES ('BT136');
INSERT INTO comp_transistors (part_number) VALUES ('BT137');
INSERT INTO comp_transistors (part_number) VALUES ('BTA10');
INSERT INTO comp_transistors (part_number) VALUES ('BTA12');
INSERT INTO comp_transistors (part_number) VALUES ('BTA16');
INSERT INTO comp_transistors (part_number) VALUES ('BZT52C5V6 (W9)');
INSERT INTO comp_transistors (part_number) VALUES ('C1740');
INSERT INTO comp_transistors (part_number) VALUES ('C18158');
INSERT INTO comp_transistors (part_number) VALUES ('C2655');
INSERT INTO comp_transistors (part_number) VALUES ('C3199');
INSERT INTO comp_transistors (part_number) VALUES ('C3421-Y');
INSERT INTO comp_transistors (part_number) VALUES ('C4408');
INSERT INTO comp_transistors (part_number) VALUES ('C945');
INSERT INTO comp_transistors (part_number) VALUES ('D313');
INSERT INTO comp_transistors (part_number) VALUES ('IRF1010');
INSERT INTO comp_transistors (part_number) VALUES ('IRF4227');
INSERT INTO comp_transistors (part_number) VALUES ('IRF540NS');
INSERT INTO comp_transistors (part_number) VALUES ('IRF630');
INSERT INTO comp_transistors (part_number) VALUES ('IRF634');
INSERT INTO comp_transistors (part_number) VALUES ('J112');
INSERT INTO comp_transistors (part_number) VALUES ('J113');
INSERT INTO comp_transistors (part_number) VALUES ('J175');
INSERT INTO comp_transistors (part_number) VALUES ('J201');
INSERT INTO comp_transistors (part_number) VALUES ('K163');
INSERT INTO comp_transistors (part_number) VALUES ('K246');
INSERT INTO comp_transistors (part_number) VALUES ('LL2705');
INSERT INTO comp_transistors (part_number) VALUES ('LM2576');
INSERT INTO comp_transistors (part_number) VALUES ('LM2596');
INSERT INTO comp_transistors (part_number) VALUES ('LM317');
INSERT INTO comp_transistors (part_number) VALUES ('LM334');
INSERT INTO comp_transistors (part_number) VALUES ('LM337');
INSERT INTO comp_transistors (part_number) VALUES ('LM35');
INSERT INTO comp_transistors (part_number) VALUES ('LM7805');
INSERT INTO comp_transistors (part_number) VALUES ('LM7808');
INSERT INTO comp_transistors (part_number) VALUES ('LM7809');
INSERT INTO comp_transistors (part_number) VALUES ('LM7812');
INSERT INTO comp_transistors (part_number) VALUES ('LM7815');
INSERT INTO comp_transistors (part_number) VALUES ('LM7909');
INSERT INTO comp_transistors (part_number) VALUES ('LM7912');
INSERT INTO comp_transistors (part_number) VALUES ('LM7915');
INSERT INTO comp_transistors (part_number) VALUES ('MBR20100');
INSERT INTO comp_transistors (part_number) VALUES ('MIC29302');
INSERT INTO comp_transistors (part_number) VALUES ('MPF102');
INSERT INTO comp_transistors (part_number) VALUES ('MPSA13');
INSERT INTO comp_transistors (part_number) VALUES ('MPSA18');
INSERT INTO comp_transistors (part_number) VALUES ('MUR1620R6');
INSERT INTO comp_transistors (part_number) VALUES ('OGBCON');
INSERT INTO comp_transistors (part_number) VALUES ('P20N06');
INSERT INTO comp_transistors (part_number) VALUES ('P20N60');
INSERT INTO comp_transistors (part_number) VALUES ('PQ10621H');
INSERT INTO comp_transistors (part_number) VALUES ('R6775');
INSERT INTO comp_transistors (part_number) VALUES ('S8050');
INSERT INTO comp_transistors (part_number) VALUES ('S8550');
INSERT INTO comp_transistors (part_number) VALUES ('S9012');
INSERT INTO comp_transistors (part_number) VALUES ('S9013');
INSERT INTO comp_transistors (part_number) VALUES ('S9014');
INSERT INTO comp_transistors (part_number) VALUES ('S9015');
INSERT INTO comp_transistors (part_number) VALUES ('SK3050');
INSERT INTO comp_transistors (part_number) VALUES ('SRF2060L');
INSERT INTO comp_transistors (part_number) VALUES ('SS13J532R');
INSERT INTO comp_transistors (part_number) VALUES ('TF8N80');
INSERT INTO comp_transistors (part_number) VALUES ('TL431A');
INSERT INTO comp_transistors (part_number) VALUES ('TOP224YN');
INSERT INTO comp_transistors (part_number) VALUES ('TSF1060M');
INSERT INTO comp_transistors (part_number) VALUES ('TSP73801DCQR');
INSERT INTO comp_transistors (part_number) VALUES ('LM2940CT');
INSERT INTO comp_transistors (part_number) VALUES ('LA4597');
INSERT INTO comp_transistors (part_number) VALUES ('TJ20A10M3');
INSERT INTO comp_transistors (part_number) VALUES ('2N7002');
INSERT INTO comp_transistors (part_number) VALUES ('PMV31XN');
INSERT INTO comp_transistors (part_number) VALUES ('LM723');
INSERT INTO comp_transistors (part_number) VALUES ('PC900');
INSERT INTO comp_transistors (part_number) VALUES ('2SC5395');
INSERT INTO comp_transistors (part_number) VALUES ('XC6701B502PRG');
INSERT INTO comp_transistors (part_number) VALUES ('F8NG');
INSERT INTO comp_diodes (part_number) VALUES ('1SS367');
INSERT INTO comp_diodes (part_number) VALUES ('BZT52C11 (WG)');
INSERT INTO comp_diodes (part_number) VALUES ('MBR0540W');
INSERT INTO comp_diodes (part_number) VALUES ('1N4148 SMD');
INSERT INTO comp_diodes (part_number) VALUES ('LL4148');
INSERT INTO comp_diodes (part_number) VALUES ('BTA42');
INSERT INTO comp_diodes (part_number) VALUES ('ZENER 3.6');
INSERT INTO comp_diodes (part_number) VALUES ('ZENER 9.1');
INSERT INTO comp_diodes (part_number) VALUES ('ZENER 5.1');
INSERT INTO comp_diodes (part_number) VALUES ('1N5353B');
INSERT INTO comp_diodes (part_number) VALUES ('1N5822');
INSERT INTO comp_diodes (part_number) VALUES ('M1');
INSERT INTO comp_diodes (part_number) VALUES ('M4');
INSERT INTO comp_diodes (part_number) VALUES ('M7');
INSERT INTO comp_diodes (part_number) VALUES ('S1M');
INSERT INTO comp_diodes (part_number) VALUES ('S2M');
INSERT INTO comp_diodes (part_number) VALUES ('S3M');
INSERT INTO comp_diodes (part_number) VALUES ('RS1M');
INSERT INTO comp_diodes (part_number) VALUES ('US1M');
INSERT INTO comp_diodes (part_number) VALUES ('SS14');
INSERT INTO comp_diodes (part_number) VALUES ('SS16');
INSERT INTO comp_diodes (part_number) VALUES ('SS24');
INSERT INTO comp_diodes (part_number) VALUES ('SS34');
INSERT INTO comp_diodes (part_number) VALUES ('SS36');
INSERT INTO comp_diodes (part_number) VALUES ('1M4007');
INSERT INTO comp_diodes (part_number) VALUES ('ZENER BZT52C11');
INSERT INTO comp_diodes (part_number) VALUES ('1N5408');
INSERT INTO comp_diodes (part_number) VALUES ('ZENER BZT52C5V6');