-- CIRUJANO DB - Componentes desde Excel (dinámico)
-- Generado: 2026-01-06 00:25:00

INSERT INTO comp_n° (value) VALUES ('1.0');
INSERT INTO comp_n° (value) VALUES ('2.0');
INSERT INTO comp_n° (value) VALUES ('3.0');
INSERT INTO comp_n° (value) VALUES ('4.0');
INSERT INTO comp_n° (value) VALUES ('5.0');
INSERT INTO comp_n° (value) VALUES ('6.0');
INSERT INTO comp_n° (value) VALUES ('7.0');
INSERT INTO comp_n° (value) VALUES ('8.0');
INSERT INTO comp_n° (value) VALUES ('9.0');
INSERT INTO comp_n° (value) VALUES ('10.0');
INSERT INTO comp_n° (value) VALUES ('11.0');
INSERT INTO comp_n° (value) VALUES ('12.0');
INSERT INTO comp_n° (value) VALUES ('13.0');
INSERT INTO comp_n° (value) VALUES ('14.0');
INSERT INTO comp_n° (value) VALUES ('15.0');
INSERT INTO comp_n° (value) VALUES ('16.0');
INSERT INTO comp_n° (value) VALUES ('17.0');
INSERT INTO comp_n° (value) VALUES ('18.0');
INSERT INTO comp_n° (value) VALUES ('19.0');
INSERT INTO comp_n° (value) VALUES ('20.0');
INSERT INTO comp_n° (value) VALUES ('21.0');
INSERT INTO comp_n° (value) VALUES ('22.0');
INSERT INTO comp_n° (value) VALUES ('23.0');
INSERT INTO comp_n° (value) VALUES ('24.0');
INSERT INTO comp_n° (value) VALUES ('25.0');
INSERT INTO comp_n° (value) VALUES ('26.0');
INSERT INTO comp_n° (value) VALUES ('27.0');
INSERT INTO comp_n° (value) VALUES ('28.0');
INSERT INTO comp_n° (value) VALUES ('29.0');
INSERT INTO comp_n° (value) VALUES ('30.0');
INSERT INTO comp_n° (value) VALUES ('31.0');
INSERT INTO comp_n° (value) VALUES ('32.0');
INSERT INTO comp_n° (value) VALUES ('33.0');
INSERT INTO comp_n° (value) VALUES ('34.0');
INSERT INTO comp_n° (value) VALUES ('35.0');
INSERT INTO comp_n° (value) VALUES ('36.0');
INSERT INTO comp_n° (value) VALUES ('37.0');
INSERT INTO comp_n° (value) VALUES ('38.0');
INSERT INTO comp_n° (value) VALUES ('39.0');
INSERT INTO comp_n° (value) VALUES ('40.0');
INSERT INTO comp_n° (value) VALUES ('41.0');
INSERT INTO comp_n° (value) VALUES ('42.0');
INSERT INTO comp_n° (value) VALUES ('43.0');
INSERT INTO comp_n° (value) VALUES ('44.0');
INSERT INTO comp_n° (value) VALUES ('45.0');
INSERT INTO comp_n° (value) VALUES ('46.0');
INSERT INTO comp_n° (value) VALUES ('47.0');
INSERT INTO comp_n° (value) VALUES ('48.0');
INSERT INTO comp_n° (value) VALUES ('49.0');
INSERT INTO comp_n° (value) VALUES ('50.0');
INSERT INTO comp_n° (value) VALUES ('51.0');
INSERT INTO comp_n° (value) VALUES ('52.0');
INSERT INTO comp_n° (value) VALUES ('53.0');
INSERT INTO comp_n° (value) VALUES ('54.0');
INSERT INTO comp_n° (value) VALUES ('55.0');
INSERT INTO comp_n° (value) VALUES ('56.0');
INSERT INTO comp_n° (value) VALUES ('57.0');
INSERT INTO comp_n° (value) VALUES ('58.0');
INSERT INTO comp_n° (value) VALUES ('59.0');
INSERT INTO comp_n° (value) VALUES ('60.0');
INSERT INTO comp_n° (value) VALUES ('61.0');
INSERT INTO comp_n° (value) VALUES ('62.0');
INSERT INTO comp_n° (value) VALUES ('63.0');
INSERT INTO comp_n° (value) VALUES ('64.0');
INSERT INTO comp_n° (value) VALUES ('65.0');
INSERT INTO comp_n° (value) VALUES ('66.0');
INSERT INTO comp_n° (value) VALUES ('67.0');
INSERT INTO comp_n° (value) VALUES ('68.0');
INSERT INTO comp_n° (value) VALUES ('69.0');
INSERT INTO comp_n° (value) VALUES ('70.0');
INSERT INTO comp_n° (value) VALUES ('71.0');
INSERT INTO comp_n° (value) VALUES ('72.0');
INSERT INTO comp_n° (value) VALUES ('73.0');
INSERT INTO comp_n° (value) VALUES ('74.0');
INSERT INTO comp_n° (value) VALUES ('75.0');
INSERT INTO comp_n° (value) VALUES ('76.0');
INSERT INTO comp_n° (value) VALUES ('77.0');
INSERT INTO comp_n° (value) VALUES ('78.0');
INSERT INTO comp_n° (value) VALUES ('79.0');
INSERT INTO comp_n° (value) VALUES ('80.0');
INSERT INTO comp_n° (value) VALUES ('81.0');
INSERT INTO comp_n° (value) VALUES ('82.0');
INSERT INTO comp_n° (value) VALUES ('83.0');
INSERT INTO comp_n° (value) VALUES ('84.0');
INSERT INTO comp_n° (value) VALUES ('85.0');
INSERT INTO comp_n° (value) VALUES ('86.0');
INSERT INTO comp_n° (value) VALUES ('87.0');
INSERT INTO comp_n° (value) VALUES ('88.0');
INSERT INTO comp_n° (value) VALUES ('89.0');
INSERT INTO comp_n° (value) VALUES ('90.0');
INSERT INTO comp_n° (value) VALUES ('91.0');
INSERT INTO comp_n° (value) VALUES ('92.0');
INSERT INTO comp_n° (value) VALUES ('93.0');
INSERT INTO comp_n° (value) VALUES ('94.0');
INSERT INTO comp_n° (value) VALUES ('95.0');
INSERT INTO comp_n° (value) VALUES ('96.0');
INSERT INTO comp_n° (value) VALUES ('97.0');
INSERT INTO comp_n° (value) VALUES ('98.0');
INSERT INTO comp_n° (value) VALUES ('99.0');
INSERT INTO comp_n° (value) VALUES ('100.0');
INSERT INTO comp_n° (value) VALUES ('101.0');
INSERT INTO comp_n° (value) VALUES ('102.0');
INSERT INTO comp_n° (value) VALUES ('103.0');
INSERT INTO comp_n° (value) VALUES ('104.0');
INSERT INTO comp_n° (value) VALUES ('105.0');
INSERT INTO comp_n° (value) VALUES ('106.0');
INSERT INTO comp_n° (value) VALUES ('107.0');
INSERT INTO comp_n° (value) VALUES ('108.0');
INSERT INTO comp_n° (value) VALUES ('109.0');
INSERT INTO comp_n° (value) VALUES ('110.0');
INSERT INTO comp_n° (value) VALUES ('111.0');
INSERT INTO comp_n° (value) VALUES ('112.0');
INSERT INTO comp_n° (value) VALUES ('113.0');
INSERT INTO comp_n° (value) VALUES ('114.0');
INSERT INTO comp_n° (value) VALUES ('115.0');
INSERT INTO comp_n° (value) VALUES ('116.0');
INSERT INTO comp_n° (value) VALUES ('117.0');
INSERT INTO comp_n° (value) VALUES ('118.0');
INSERT INTO comp_n° (value) VALUES ('119.0');
INSERT INTO comp_n° (value) VALUES ('120.0');
INSERT INTO comp_n° (value) VALUES ('121.0');
INSERT INTO comp_n° (value) VALUES ('122.0');
INSERT INTO comp_n° (value) VALUES ('123.0');
INSERT INTO comp_n° (value) VALUES ('124.0');
INSERT INTO comp_n° (value) VALUES ('125.0');
INSERT INTO comp_n° (value) VALUES ('126.0');
INSERT INTO comp_n° (value) VALUES ('127.0');
INSERT INTO comp_n° (value) VALUES ('128.0');
INSERT INTO comp_n° (value) VALUES ('129.0');
INSERT INTO comp_n° (value) VALUES ('130.0');
INSERT INTO comp_n° (value) VALUES ('131.0');
INSERT INTO comp_n° (value) VALUES ('132.0');
INSERT INTO comp_n° (value) VALUES ('133.0');
INSERT INTO comp_n° (value) VALUES ('134.0');
INSERT INTO comp_n° (value) VALUES ('135.0');
INSERT INTO comp_n° (value) VALUES ('136.0');
INSERT INTO comp_n° (value) VALUES ('137.0');
INSERT INTO comp_n° (value) VALUES ('138.0');
INSERT INTO comp_n° (value) VALUES ('139.0');
INSERT INTO comp_n° (value) VALUES ('140.0');
INSERT INTO comp_n° (value) VALUES ('141.0');
INSERT INTO comp_n° (value) VALUES ('142.0');
INSERT INTO comp_n° (value) VALUES ('143.0');
INSERT INTO comp_n° (value) VALUES ('144.0');
INSERT INTO comp_n° (value) VALUES ('145.0');
INSERT INTO comp_n° (value) VALUES ('146.0');
INSERT INTO comp_n° (value) VALUES ('147.0');
INSERT INTO comp_n° (value) VALUES ('148.0');
INSERT INTO comp_n° (value) VALUES ('149.0');
INSERT INTO comp_n° (value) VALUES ('150.0');
INSERT INTO comp_n° (value) VALUES ('151.0');
INSERT INTO comp_n° (value) VALUES ('152.0');
INSERT INTO comp_n° (value) VALUES ('153.0');
INSERT INTO comp_n° (value) VALUES ('154.0');
INSERT INTO comp_n° (value) VALUES ('155.0');
INSERT INTO comp_n° (value) VALUES ('156.0');
INSERT INTO comp_n° (value) VALUES ('157.0');
INSERT INTO comp_n° (value) VALUES ('158.0');
INSERT INTO comp_n° (value) VALUES ('159.0');
INSERT INTO comp_n° (value) VALUES ('160.0');
INSERT INTO comp_n° (value) VALUES ('161.0');
INSERT INTO comp_n° (value) VALUES ('162.0');
INSERT INTO comp_n° (value) VALUES ('163.0');
INSERT INTO comp_n° (value) VALUES ('164.0');
INSERT INTO comp_n° (value) VALUES ('165.0');
INSERT INTO comp_n° (value) VALUES ('166.0');
INSERT INTO comp_n° (value) VALUES ('167.0');
INSERT INTO comp_n° (value) VALUES ('168.0');
INSERT INTO comp_resistencias (value) VALUES ('0.33');
INSERT INTO comp_resistencias (value) VALUES ('0.5');
INSERT INTO comp_resistencias (value) VALUES ('0.6');
INSERT INTO comp_resistencias (value) VALUES ('1.0');
INSERT INTO comp_resistencias (value) VALUES ('1.2');
INSERT INTO comp_resistencias (value) VALUES ('1.3');
INSERT INTO comp_resistencias (value) VALUES ('1.5');
INSERT INTO comp_resistencias (value) VALUES ('1.8');
INSERT INTO comp_resistencias (value) VALUES ('2.0');
INSERT INTO comp_resistencias (value) VALUES ('2.2');
INSERT INTO comp_resistencias (value) VALUES ('2.4');
INSERT INTO comp_resistencias (value) VALUES ('2.7');
INSERT INTO comp_resistencias (value) VALUES ('3.0');
INSERT INTO comp_resistencias (value) VALUES ('3.3');
INSERT INTO comp_resistencias (value) VALUES ('3.6');
INSERT INTO comp_resistencias (value) VALUES ('3.9');
INSERT INTO comp_resistencias (value) VALUES ('4.3');
INSERT INTO comp_resistencias (value) VALUES ('4.7');
INSERT INTO comp_resistencias (value) VALUES ('5.1');
INSERT INTO comp_resistencias (value) VALUES ('5.6');
INSERT INTO comp_resistencias (value) VALUES ('6.2');
INSERT INTO comp_resistencias (value) VALUES ('6.8');
INSERT INTO comp_resistencias (value) VALUES ('7.5');
INSERT INTO comp_resistencias (value) VALUES ('8.2');
INSERT INTO comp_resistencias (value) VALUES ('9.1');
INSERT INTO comp_resistencias (value) VALUES ('10.0');
INSERT INTO comp_resistencias (value) VALUES ('11.0');
INSERT INTO comp_resistencias (value) VALUES ('12.0');
INSERT INTO comp_resistencias (value) VALUES ('15.0');
INSERT INTO comp_resistencias (value) VALUES ('18.0');
INSERT INTO comp_resistencias (value) VALUES ('20.0');
INSERT INTO comp_resistencias (value) VALUES ('21.0');
INSERT INTO comp_resistencias (value) VALUES ('22.0');
INSERT INTO comp_resistencias (value) VALUES ('24.0');
INSERT INTO comp_resistencias (value) VALUES ('27.0');
INSERT INTO comp_resistencias (value) VALUES ('30.0');
INSERT INTO comp_resistencias (value) VALUES ('33.0');
INSERT INTO comp_resistencias (value) VALUES ('36.0');
INSERT INTO comp_resistencias (value) VALUES ('39.0');
INSERT INTO comp_resistencias (value) VALUES ('43.0');
INSERT INTO comp_resistencias (value) VALUES ('47.0');
INSERT INTO comp_resistencias (value) VALUES ('51.0');
INSERT INTO comp_resistencias (value) VALUES ('56.0');
INSERT INTO comp_resistencias (value) VALUES ('62.0');
INSERT INTO comp_resistencias (value) VALUES ('68.0');
INSERT INTO comp_resistencias (value) VALUES ('75.0');
INSERT INTO comp_resistencias (value) VALUES ('82.0');
INSERT INTO comp_resistencias (value) VALUES ('91.0');
INSERT INTO comp_resistencias (value) VALUES ('100.0');
INSERT INTO comp_resistencias (value) VALUES ('110.0');
INSERT INTO comp_resistencias (value) VALUES ('120.0');
INSERT INTO comp_resistencias (value) VALUES ('130.0');
INSERT INTO comp_resistencias (value) VALUES ('150.0');
INSERT INTO comp_resistencias (value) VALUES ('160.0');
INSERT INTO comp_resistencias (value) VALUES ('180.0');
INSERT INTO comp_resistencias (value) VALUES ('200.0');
INSERT INTO comp_resistencias (value) VALUES ('220.0');
INSERT INTO comp_resistencias (value) VALUES ('240.0');
INSERT INTO comp_resistencias (value) VALUES ('270.0');
INSERT INTO comp_resistencias (value) VALUES ('300.0');
INSERT INTO comp_resistencias (value) VALUES ('330.0');
INSERT INTO comp_resistencias (value) VALUES ('360.0');
INSERT INTO comp_resistencias (value) VALUES ('390.0');
INSERT INTO comp_resistencias (value) VALUES ('430.0');
INSERT INTO comp_resistencias (value) VALUES ('470.0');
INSERT INTO comp_resistencias (value) VALUES ('510.0');
INSERT INTO comp_resistencias (value) VALUES ('560.0');
INSERT INTO comp_resistencias (value) VALUES ('620.0');
INSERT INTO comp_resistencias (value) VALUES ('680.0');
INSERT INTO comp_resistencias (value) VALUES ('750.0');
INSERT INTO comp_resistencias (value) VALUES ('820.0');
INSERT INTO comp_resistencias (value) VALUES ('825.0');
INSERT INTO comp_resistencias (value) VALUES ('845.0');
INSERT INTO comp_resistencias (value) VALUES ('910.0');
INSERT INTO comp_resistencias (value) VALUES ('1000.0');
INSERT INTO comp_resistencias (value) VALUES ('1100.0');
INSERT INTO comp_resistencias (value) VALUES ('1200.0');
INSERT INTO comp_resistencias (value) VALUES ('1500.0');
INSERT INTO comp_resistencias (value) VALUES ('1600.0');
INSERT INTO comp_resistencias (value) VALUES ('1800.0');
INSERT INTO comp_resistencias (value) VALUES ('2000.0');
INSERT INTO comp_resistencias (value) VALUES ('2200.0');
INSERT INTO comp_resistencias (value) VALUES ('2400.0');
INSERT INTO comp_resistencias (value) VALUES ('2700.0');
INSERT INTO comp_resistencias (value) VALUES ('3000.0');
INSERT INTO comp_resistencias (value) VALUES ('3300.0');
INSERT INTO comp_resistencias (value) VALUES ('3600.0');
INSERT INTO comp_resistencias (value) VALUES ('3900.0');
INSERT INTO comp_resistencias (value) VALUES ('4300.0');
INSERT INTO comp_resistencias (value) VALUES ('4700.0');
INSERT INTO comp_resistencias (value) VALUES ('4900.0');
INSERT INTO comp_resistencias (value) VALUES ('5100.0');
INSERT INTO comp_resistencias (value) VALUES ('5600.0');
INSERT INTO comp_resistencias (value) VALUES ('6200.0');
INSERT INTO comp_resistencias (value) VALUES ('6800.0');
INSERT INTO comp_resistencias (value) VALUES ('7500.0');
INSERT INTO comp_resistencias (value) VALUES ('7870.0');
INSERT INTO comp_resistencias (value) VALUES ('8200.0');
INSERT INTO comp_resistencias (value) VALUES ('9100.0');
INSERT INTO comp_resistencias (value) VALUES ('10000.0');
INSERT INTO comp_resistencias (value) VALUES ('11000.0');
INSERT INTO comp_resistencias (value) VALUES ('12000.0');
INSERT INTO comp_resistencias (value) VALUES ('13000.0');
INSERT INTO comp_resistencias (value) VALUES ('15000.0');
INSERT INTO comp_resistencias (value) VALUES ('16000.0');
INSERT INTO comp_resistencias (value) VALUES ('16200.0');
INSERT INTO comp_resistencias (value) VALUES ('18000.0');
INSERT INTO comp_resistencias (value) VALUES ('20000.0');
INSERT INTO comp_resistencias (value) VALUES ('22000.0');
INSERT INTO comp_resistencias (value) VALUES ('24000.0');
INSERT INTO comp_resistencias (value) VALUES ('27000.0');
INSERT INTO comp_resistencias (value) VALUES ('30000.0');
INSERT INTO comp_resistencias (value) VALUES ('33000.0');
INSERT INTO comp_resistencias (value) VALUES ('34600.0');
INSERT INTO comp_resistencias (value) VALUES ('36000.0');
INSERT INTO comp_resistencias (value) VALUES ('39000.0');
INSERT INTO comp_resistencias (value) VALUES ('43000.0');
INSERT INTO comp_resistencias (value) VALUES ('47000.0');
INSERT INTO comp_resistencias (value) VALUES ('51000.0');
INSERT INTO comp_resistencias (value) VALUES ('53000.0');
INSERT INTO comp_resistencias (value) VALUES ('56000.0');
INSERT INTO comp_resistencias (value) VALUES ('62000.0');
INSERT INTO comp_resistencias (value) VALUES ('63400.0');
INSERT INTO comp_resistencias (value) VALUES ('68000.0');
INSERT INTO comp_resistencias (value) VALUES ('68100.0');
INSERT INTO comp_resistencias (value) VALUES ('75000.0');
INSERT INTO comp_resistencias (value) VALUES ('82000.0');
INSERT INTO comp_resistencias (value) VALUES ('91000.0');
INSERT INTO comp_resistencias (value) VALUES ('100000.0');
INSERT INTO comp_resistencias (value) VALUES ('110000.0');
INSERT INTO comp_resistencias (value) VALUES ('120000.0');
INSERT INTO comp_resistencias (value) VALUES ('127000.0');
INSERT INTO comp_resistencias (value) VALUES ('130000.0');
INSERT INTO comp_resistencias (value) VALUES ('150000.0');
INSERT INTO comp_resistencias (value) VALUES ('160000.0');
INSERT INTO comp_resistencias (value) VALUES ('180000.0');
INSERT INTO comp_resistencias (value) VALUES ('200000.0');
INSERT INTO comp_resistencias (value) VALUES ('220000.0');
INSERT INTO comp_resistencias (value) VALUES ('240000.0');
INSERT INTO comp_resistencias (value) VALUES ('270000.0');
INSERT INTO comp_resistencias (value) VALUES ('300000.0');
INSERT INTO comp_resistencias (value) VALUES ('330000.0');
INSERT INTO comp_resistencias (value) VALUES ('360000.0');
INSERT INTO comp_resistencias (value) VALUES ('390000.0');
INSERT INTO comp_resistencias (value) VALUES ('430000.0');
INSERT INTO comp_resistencias (value) VALUES ('470000.0');
INSERT INTO comp_resistencias (value) VALUES ('510000.0');
INSERT INTO comp_resistencias (value) VALUES ('560000.0');
INSERT INTO comp_resistencias (value) VALUES ('620000.0');
INSERT INTO comp_resistencias (value) VALUES ('680000.0');
INSERT INTO comp_resistencias (value) VALUES ('750000.0');
INSERT INTO comp_resistencias (value) VALUES ('820000.0');
INSERT INTO comp_resistencias (value) VALUES ('910000.0');
INSERT INTO comp_resistencias (value) VALUES ('1000000.0');
INSERT INTO comp_resistencias (value) VALUES ('1200000.0');
INSERT INTO comp_resistencias (value) VALUES ('1500000.0');
INSERT INTO comp_resistencias (value) VALUES ('1800000.0');
INSERT INTO comp_resistencias (value) VALUES ('2200000.0');
INSERT INTO comp_resistencias (value) VALUES ('2400000.0');
INSERT INTO comp_resistencias (value) VALUES ('3000000.0');
INSERT INTO comp_resistencias (value) VALUES ('3300000.0');
INSERT INTO comp_resistencias (value) VALUES ('3900000.0');
INSERT INTO comp_resistencias (value) VALUES ('4700000.0');
INSERT INTO comp_resistencias (value) VALUES ('5100000.0');
INSERT INTO comp_resistencias (value) VALUES ('5600000.0');
INSERT INTO comp_resistencias (value) VALUES ('6800000.0');
INSERT INTO comp_resistencias (value) VALUES ('8200000.0');
INSERT INTO comp_resistencias (value) VALUES ('10000000.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('1.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('2.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('3.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('4.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('5.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('6.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('7.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('8.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('9.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('10.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('15.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('18.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('20.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('22.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('27.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('30.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('33.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('40.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('47.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('50.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('56.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('60.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('68.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('75.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('82.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('100.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('101.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('101.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('102.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('103.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('104.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('105.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('106.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('121.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('141.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('150.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('151.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('152.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('153.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('154.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('181.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('201.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('202.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('203.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('220.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('221.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('221.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('222.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('223.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('224.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('254.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('271.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('273.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('300.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('304.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('331.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('332.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('333.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('334.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('385.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('442.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('470.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('471.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('472.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('473.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('474.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('561.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('562.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('564.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('604.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('681.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('682.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('683.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('821.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('822.0');
INSERT INTO comp_capacitores_ceramicos (value) VALUES ('823.0');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('0.1');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('0.22');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('0.47');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('0.68');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('1');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('2');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('2.2');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('3.3');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('4.7');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('6.8');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('10');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('10NP');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('22');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('33');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('47');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('100');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('220');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('1000');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('3300');
INSERT INTO comp_capacitores_electroliticos (value) VALUES ('4700');
INSERT INTO comp_transistores (value) VALUES ('20N60');
INSERT INTO comp_transistores (value) VALUES ('2387A');
INSERT INTO comp_transistores (value) VALUES ('2387A');
INSERT INTO comp_transistores (value) VALUES ('2N222');
INSERT INTO comp_transistores (value) VALUES ('2N2907');
INSERT INTO comp_transistores (value) VALUES ('2N3904');
INSERT INTO comp_transistores (value) VALUES ('2N3906');
INSERT INTO comp_transistores (value) VALUES ('2N4401');
INSERT INTO comp_transistores (value) VALUES ('2N5087');
INSERT INTO comp_transistores (value) VALUES ('2N5088');
INSERT INTO comp_transistores (value) VALUES ('2N5089');
INSERT INTO comp_transistores (value) VALUES ('2N5401');
INSERT INTO comp_transistores (value) VALUES ('2N5457');
INSERT INTO comp_transistores (value) VALUES ('2N5458');
INSERT INTO comp_transistores (value) VALUES ('2N5460');
INSERT INTO comp_transistores (value) VALUES ('2N5551');
INSERT INTO comp_transistores (value) VALUES ('2N6111G');
INSERT INTO comp_transistores (value) VALUES ('2SA1037AK (FR)');
INSERT INTO comp_transistores (value) VALUES ('2SC2060');
INSERT INTO comp_transistores (value) VALUES ('2SC4207-Y');
INSERT INTO comp_transistores (value) VALUES ('2SK30A');
INSERT INTO comp_transistores (value) VALUES ('742669095252 (K2-2)');
INSERT INTO comp_transistores (value) VALUES ('A1015');
INSERT INTO comp_transistores (value) VALUES ('A1273');
INSERT INTO comp_transistores (value) VALUES ('A42');
INSERT INTO comp_transistores (value) VALUES ('A933');
INSERT INTO comp_transistores (value) VALUES ('AZ1117');
INSERT INTO comp_transistores (value) VALUES ('B1342');
INSERT INTO comp_transistores (value) VALUES ('B1568');
INSERT INTO comp_transistores (value) VALUES ('B772P');
INSERT INTO comp_transistores (value) VALUES ('B824');
INSERT INTO comp_transistores (value) VALUES ('BC327');
INSERT INTO comp_transistores (value) VALUES ('BC337');
INSERT INTO comp_transistores (value) VALUES ('BC517');
INSERT INTO comp_transistores (value) VALUES ('BC547');
INSERT INTO comp_transistores (value) VALUES ('BC548');
INSERT INTO comp_transistores (value) VALUES ('BC549');
INSERT INTO comp_transistores (value) VALUES ('BC550');
INSERT INTO comp_transistores (value) VALUES ('BC556');
INSERT INTO comp_transistores (value) VALUES ('BC557');
INSERT INTO comp_transistores (value) VALUES ('BC558');
INSERT INTO comp_transistores (value) VALUES ('BC847PN');
INSERT INTO comp_transistores (value) VALUES ('BD138');
INSERT INTO comp_transistores (value) VALUES ('BD438');
INSERT INTO comp_transistores (value) VALUES ('BD651');
INSERT INTO comp_transistores (value) VALUES ('BS170');
INSERT INTO comp_transistores (value) VALUES ('BT136');
INSERT INTO comp_transistores (value) VALUES ('BT137');
INSERT INTO comp_transistores (value) VALUES ('BTA10');
INSERT INTO comp_transistores (value) VALUES ('BTA12');
INSERT INTO comp_transistores (value) VALUES ('BTA16');
INSERT INTO comp_transistores (value) VALUES ('BZT52C5V6 (W9)');
INSERT INTO comp_transistores (value) VALUES ('C1740');
INSERT INTO comp_transistores (value) VALUES ('C18158');
INSERT INTO comp_transistores (value) VALUES ('C2655');
INSERT INTO comp_transistores (value) VALUES ('C3199');
INSERT INTO comp_transistores (value) VALUES ('C3421-Y');
INSERT INTO comp_transistores (value) VALUES ('C4408');
INSERT INTO comp_transistores (value) VALUES ('C945');
INSERT INTO comp_transistores (value) VALUES ('D313');
INSERT INTO comp_transistores (value) VALUES ('IRF1010');
INSERT INTO comp_transistores (value) VALUES ('IRF4227');
INSERT INTO comp_transistores (value) VALUES ('IRF540NS');
INSERT INTO comp_transistores (value) VALUES ('IRF630');
INSERT INTO comp_transistores (value) VALUES ('IRF634');
INSERT INTO comp_transistores (value) VALUES ('J112');
INSERT INTO comp_transistores (value) VALUES ('J113');
INSERT INTO comp_transistores (value) VALUES ('J175');
INSERT INTO comp_transistores (value) VALUES ('J201');
INSERT INTO comp_transistores (value) VALUES ('K163');
INSERT INTO comp_transistores (value) VALUES ('K246');
INSERT INTO comp_transistores (value) VALUES ('LL2705');
INSERT INTO comp_transistores (value) VALUES ('LM2576');
INSERT INTO comp_transistores (value) VALUES ('LM2596');
INSERT INTO comp_transistores (value) VALUES ('LM317');
INSERT INTO comp_transistores (value) VALUES ('LM334');
INSERT INTO comp_transistores (value) VALUES ('LM337');
INSERT INTO comp_transistores (value) VALUES ('LM35');
INSERT INTO comp_transistores (value) VALUES ('LM7805');
INSERT INTO comp_transistores (value) VALUES ('LM7805');
INSERT INTO comp_transistores (value) VALUES ('LM7808');
INSERT INTO comp_transistores (value) VALUES ('LM7809');
INSERT INTO comp_transistores (value) VALUES ('LM7812');
INSERT INTO comp_transistores (value) VALUES ('LM7815');
INSERT INTO comp_transistores (value) VALUES ('LM7909');
INSERT INTO comp_transistores (value) VALUES ('LM7912');
INSERT INTO comp_transistores (value) VALUES ('LM7915');
INSERT INTO comp_transistores (value) VALUES ('MBR20100');
INSERT INTO comp_transistores (value) VALUES ('MIC29302');
INSERT INTO comp_transistores (value) VALUES ('MPF102');
INSERT INTO comp_transistores (value) VALUES ('MPSA13');
INSERT INTO comp_transistores (value) VALUES ('MPSA18');
INSERT INTO comp_transistores (value) VALUES ('MUR1620R6');
INSERT INTO comp_transistores (value) VALUES ('OGBCON');
INSERT INTO comp_transistores (value) VALUES ('P20N06');
INSERT INTO comp_transistores (value) VALUES ('P20N60');
INSERT INTO comp_transistores (value) VALUES ('PQ10621H');
INSERT INTO comp_transistores (value) VALUES ('R6775');
INSERT INTO comp_transistores (value) VALUES ('S8050');
INSERT INTO comp_transistores (value) VALUES ('S8550');
INSERT INTO comp_transistores (value) VALUES ('S9012');
INSERT INTO comp_transistores (value) VALUES ('S9013');
INSERT INTO comp_transistores (value) VALUES ('S9014');
INSERT INTO comp_transistores (value) VALUES ('S9015');
INSERT INTO comp_transistores (value) VALUES ('SK3050');
INSERT INTO comp_transistores (value) VALUES ('SRF2060L');
INSERT INTO comp_transistores (value) VALUES ('SS13J532R');
INSERT INTO comp_transistores (value) VALUES ('TF8N80');
INSERT INTO comp_transistores (value) VALUES ('TL431A');
INSERT INTO comp_transistores (value) VALUES ('TOP224YN');
INSERT INTO comp_transistores (value) VALUES ('TSF1060M');
INSERT INTO comp_transistores (value) VALUES ('TSP73801DCQR');
INSERT INTO comp_transistores (value) VALUES ('lm2940ct');
INSERT INTO comp_transistores (value) VALUES ('la4597');
INSERT INTO comp_transistores (value) VALUES ('tj20a10m3');
INSERT INTO comp_transistores (value) VALUES ('2n7002');
INSERT INTO comp_transistores (value) VALUES ('pmv31xn');
INSERT INTO comp_transistores (value) VALUES ('irf540ns');
INSERT INTO comp_transistores (value) VALUES ('lm723');
INSERT INTO comp_transistores (value) VALUES ('pc900');
INSERT INTO comp_transistores (value) VALUES ('2sc5395');
INSERT INTO comp_transistores (value) VALUES ('xc6701b502prg');
INSERT INTO comp_transistores (value) VALUES ('f8ng');
INSERT INTO comp_ics (value) VALUES ('7555');
INSERT INTO comp_ics (value) VALUES ('7660');
INSERT INTO comp_ics (value) VALUES ('12320VH25V');
INSERT INTO comp_ics (value) VALUES ('12F629');
INSERT INTO comp_ics (value) VALUES ('16F628');
INSERT INTO comp_ics (value) VALUES ('16F648');
INSERT INTO comp_ics (value) VALUES ('16F684');
INSERT INTO comp_ics (value) VALUES ('16F84');
INSERT INTO comp_ics (value) VALUES ('16F877');
INSERT INTO comp_ics (value) VALUES ('16F88');
INSERT INTO comp_ics (value) VALUES ('16F886');
INSERT INTO comp_ics (value) VALUES ('16F887');
INSERT INTO comp_ics (value) VALUES ('18F4520');
INSERT INTO comp_ics (value) VALUES ('18F4550');
INSERT INTO comp_ics (value) VALUES ('24LC04');
INSERT INTO comp_ics (value) VALUES ('24LC16');
INSERT INTO comp_ics (value) VALUES ('44LS157');
INSERT INTO comp_ics (value) VALUES ('4N25');
INSERT INTO comp_ics (value) VALUES ('4N26');
INSERT INTO comp_ics (value) VALUES ('4N36');
INSERT INTO comp_ics (value) VALUES ('5218A');
INSERT INTO comp_ics (value) VALUES ('6N137');
INSERT INTO comp_ics (value) VALUES ('74HC04');
INSERT INTO comp_ics (value) VALUES ('74HC132');
INSERT INTO comp_ics (value) VALUES ('74HC138');
INSERT INTO comp_ics (value) VALUES ('74HC14');
INSERT INTO comp_ics (value) VALUES ('74HC154');
INSERT INTO comp_ics (value) VALUES ('74HC245');
INSERT INTO comp_ics (value) VALUES ('74HC373');
INSERT INTO comp_ics (value) VALUES ('74HC4051');
INSERT INTO comp_ics (value) VALUES ('74HC75');
INSERT INTO comp_ics (value) VALUES ('74LS04');
INSERT INTO comp_ics (value) VALUES ('74LS08');
INSERT INTO comp_ics (value) VALUES ('74LS14');
INSERT INTO comp_ics (value) VALUES ('74LS48');
INSERT INTO comp_ics (value) VALUES ('AC3105I');
INSERT INTO comp_ics (value) VALUES ('AK4318');
INSERT INTO comp_ics (value) VALUES ('AK4526VQ');
INSERT INTO comp_ics (value) VALUES ('AN7147N');
INSERT INTO comp_ics (value) VALUES ('ATMEGA328P');
INSERT INTO comp_ics (value) VALUES ('ATTINY2313');
INSERT INTO comp_ics (value) VALUES ('ATTINY4313');
INSERT INTO comp_ics (value) VALUES ('BA5417');
INSERT INTO comp_ics (value) VALUES ('CA3046');
INSERT INTO comp_ics (value) VALUES ('CA3080');
INSERT INTO comp_ics (value) VALUES ('CD14538');
INSERT INTO comp_ics (value) VALUES ('CD40106');
INSERT INTO comp_ics (value) VALUES ('CD40109');
INSERT INTO comp_ics (value) VALUES ('CD4011');
INSERT INTO comp_ics (value) VALUES ('CD4013');
INSERT INTO comp_ics (value) VALUES ('CD4015');
INSERT INTO comp_ics (value) VALUES ('CD4016');
INSERT INTO comp_ics (value) VALUES ('CD4017');
INSERT INTO comp_ics (value) VALUES ('CD4020');
INSERT INTO comp_ics (value) VALUES ('CD4027');
INSERT INTO comp_ics (value) VALUES ('CD4029');
INSERT INTO comp_ics (value) VALUES ('CD4040');
INSERT INTO comp_ics (value) VALUES ('CD4047');
INSERT INTO comp_ics (value) VALUES ('CD4049');
INSERT INTO comp_ics (value) VALUES ('CD4051');
INSERT INTO comp_ics (value) VALUES ('CD4052');
INSERT INTO comp_ics (value) VALUES ('CD4053');
INSERT INTO comp_ics (value) VALUES ('CD4060');
INSERT INTO comp_ics (value) VALUES ('CD4066');
INSERT INTO comp_ics (value) VALUES ('CD4067');
INSERT INTO comp_ics (value) VALUES ('CD4069');
INSERT INTO comp_ics (value) VALUES ('CD4072');
INSERT INTO comp_ics (value) VALUES ('CD4073');
INSERT INTO comp_ics (value) VALUES ('CD4081');
INSERT INTO comp_ics (value) VALUES ('CD4093');
INSERT INTO comp_ics (value) VALUES ('CD4094');
INSERT INTO comp_ics (value) VALUES ('CD4096');
INSERT INTO comp_ics (value) VALUES ('CPH6302');
INSERT INTO comp_ics (value) VALUES ('D41416C');
INSERT INTO comp_ics (value) VALUES ('D72064LM');
INSERT INTO comp_ics (value) VALUES ('DG412');
INSERT INTO comp_ics (value) VALUES ('FT232RL');
INSERT INTO comp_ics (value) VALUES ('FW828');
INSERT INTO comp_ics (value) VALUES ('HJ238');
INSERT INTO comp_ics (value) VALUES ('HT8950');
INSERT INTO comp_ics (value) VALUES ('JRC2903');
INSERT INTO comp_ics (value) VALUES ('JCR4556');
INSERT INTO comp_ics (value) VALUES ('JCR4558');
INSERT INTO comp_ics (value) VALUES ('JCR4560');
INSERT INTO comp_ics (value) VALUES ('JCR4565');
INSERT INTO comp_ics (value) VALUES ('JCR4580');
INSERT INTO comp_ics (value) VALUES ('KA2206');
INSERT INTO comp_ics (value) VALUES ('KA2535');
INSERT INTO comp_ics (value) VALUES ('LA4227');
INSERT INTO comp_ics (value) VALUES ('LM051A');
INSERT INTO comp_ics (value) VALUES ('LM13600');
INSERT INTO comp_ics (value) VALUES ('LM13700');
INSERT INTO comp_ics (value) VALUES ('LM1496');
INSERT INTO comp_ics (value) VALUES ('LM1881');
INSERT INTO comp_ics (value) VALUES ('LM2574');
INSERT INTO comp_ics (value) VALUES ('LM311');
INSERT INTO comp_ics (value) VALUES ('LM324');
INSERT INTO comp_ics (value) VALUES ('LM339');
INSERT INTO comp_ics (value) VALUES ('LM3578AN');
INSERT INTO comp_ics (value) VALUES ('LM358');
INSERT INTO comp_ics (value) VALUES ('LM386');
INSERT INTO comp_ics (value) VALUES ('LM3900');
INSERT INTO comp_ics (value) VALUES ('LM393');
INSERT INTO comp_ics (value) VALUES ('LM394');
INSERT INTO comp_ics (value) VALUES ('LM741');
INSERT INTO comp_ics (value) VALUES ('LM831N');
INSERT INTO comp_ics (value) VALUES ('LNK3046N');
INSERT INTO comp_ics (value) VALUES ('LT8304');
INSERT INTO comp_ics (value) VALUES ('LV125A');
INSERT INTO comp_ics (value) VALUES ('MAX1044');
INSERT INTO comp_ics (value) VALUES ('MAX232');
INSERT INTO comp_ics (value) VALUES ('MB81C4526A');
INSERT INTO comp_ics (value) VALUES ('MC1489');
INSERT INTO comp_ics (value) VALUES ('MCP4822');
INSERT INTO comp_ics (value) VALUES ('MCP6004');
INSERT INTO comp_ics (value) VALUES ('MOC3021');
INSERT INTO comp_ics (value) VALUES ('MP1470GJ');
INSERT INTO comp_ics (value) VALUES ('MX7528');
INSERT INTO comp_ics (value) VALUES ('NE5532');
INSERT INTO comp_ics (value) VALUES ('NE5534');
INSERT INTO comp_ics (value) VALUES ('NE555');
INSERT INTO comp_ics (value) VALUES ('NE556');
INSERT INTO comp_ics (value) VALUES ('NE567');
INSERT INTO comp_ics (value) VALUES ('NJM2374');
INSERT INTO comp_ics (value) VALUES ('NNC6.2MG-T1');
INSERT INTO comp_ics (value) VALUES ('OB2269CP');
INSERT INTO comp_ics (value) VALUES ('OP07');
INSERT INTO comp_ics (value) VALUES ('OPA2137PA');
INSERT INTO comp_ics (value) VALUES ('PC2581V');
INSERT INTO comp_ics (value) VALUES ('PCA9532');
INSERT INTO comp_ics (value) VALUES ('PT2399');
INSERT INTO comp_ics (value) VALUES ('RN5RG33AA');
INSERT INTO comp_ics (value) VALUES ('RRL025P03TR');
INSERT INTO comp_ics (value) VALUES ('SM76489AN');
INSERT INTO comp_ics (value) VALUES ('SN74157');
INSERT INTO comp_ics (value) VALUES ('SN74173');
INSERT INTO comp_ics (value) VALUES ('SN75176');
INSERT INTO comp_ics (value) VALUES ('SN75240W');
INSERT INTO comp_ics (value) VALUES ('SN754410');
INSERT INTO comp_ics (value) VALUES ('TDA2822M');
INSERT INTO comp_ics (value) VALUES ('TDA7294');
INSERT INTO comp_ics (value) VALUES ('TDA9108');
INSERT INTO comp_ics (value) VALUES ('TEA2025');
INSERT INTO comp_ics (value) VALUES ('THAT1646');
INSERT INTO comp_ics (value) VALUES ('TL071');
INSERT INTO comp_ics (value) VALUES ('TL072');
INSERT INTO comp_ics (value) VALUES ('TL074');
INSERT INTO comp_ics (value) VALUES ('TL082');
INSERT INTO comp_ics (value) VALUES ('TL084');
INSERT INTO comp_ics (value) VALUES ('TLC2272');
INSERT INTO comp_ics (value) VALUES ('TLC5940');
INSERT INTO comp_ics (value) VALUES ('TMS4145');
INSERT INTO comp_ics (value) VALUES ('TPS54240DGQR');
INSERT INTO comp_ics (value) VALUES ('TPS5430');
INSERT INTO comp_ics (value) VALUES ('TPS7A3401DGNR');
INSERT INTO comp_ics (value) VALUES ('TSB41AB2');
INSERT INTO comp_ics (value) VALUES ('TUSB3200');
INSERT INTO comp_ics (value) VALUES ('UC3843');
INSERT INTO comp_ics (value) VALUES ('UL26');
INSERT INTO comp_ics (value) VALUES ('UMG9NTR (G9)');
INSERT INTO comp_ics (value) VALUES ('USB3343');
INSERT INTO comp_ics (value) VALUES ('V54C3256164VDI7');
INSERT INTO comp_ics (value) VALUES ('VA220M');
INSERT INTO comp_ics (value) VALUES ('WOOA');
INSERT INTO comp_ics (value) VALUES ('P721F');
INSERT INTO comp_ics (value) VALUES ('upc4570ha');
INSERT INTO comp_ics (value) VALUES ('yda176');
INSERT INTO comp_ics (value) VALUES ('ht6116-70');
INSERT INTO comp_ics (value) VALUES ('upd63200gs');
INSERT INTO comp_ics (value) VALUES ('23l256i');
INSERT INTO comp_ics (value) VALUES ('74hc166');
INSERT INTO comp_ics (value) VALUES ('mc14556b');
INSERT INTO comp_ics (value) VALUES ('sn74ls90n');
INSERT INTO comp_diodos (value) VALUES ('1SS367');
INSERT INTO comp_diodos (value) VALUES ('BZT52C11 (WG)');
INSERT INTO comp_diodos (value) VALUES ('MBR0540W');
INSERT INTO comp_diodos (value) VALUES ('1n4148 smd');
INSERT INTO comp_diodos (value) VALUES ('ll4148');
INSERT INTO comp_diodos (value) VALUES ('BTA42');
INSERT INTO comp_diodos (value) VALUES ('zener 3.6');
INSERT INTO comp_diodos (value) VALUES ('zener 9.1');
INSERT INTO comp_diodos (value) VALUES ('zener 5.1');
INSERT INTO comp_diodos (value) VALUES ('1n5353b');
INSERT INTO comp_diodos (value) VALUES ('1n5822');
INSERT INTO comp_diodos (value) VALUES ('m1');
INSERT INTO comp_diodos (value) VALUES ('m4');
INSERT INTO comp_diodos (value) VALUES ('m7');
INSERT INTO comp_diodos (value) VALUES ('s1m');
INSERT INTO comp_diodos (value) VALUES ('s2m');
INSERT INTO comp_diodos (value) VALUES ('s3m');
INSERT INTO comp_diodos (value) VALUES ('rs1m');
INSERT INTO comp_diodos (value) VALUES ('us1m');
INSERT INTO comp_diodos (value) VALUES ('ss14');
INSERT INTO comp_diodos (value) VALUES ('ss16');
INSERT INTO comp_diodos (value) VALUES ('ss24');
INSERT INTO comp_diodos (value) VALUES ('ss34');
INSERT INTO comp_diodos (value) VALUES ('ss36');
INSERT INTO comp_diodos (value) VALUES ('1m4007');
INSERT INTO comp_diodos (value) VALUES ('zener bzt52c11');
INSERT INTO comp_diodos (value) VALUES ('1n5408');
INSERT INTO comp_diodos (value) VALUES ('zener bzt52c5v6');
INSERT INTO comp_diodos (value) VALUES ('1ss367');
INSERT INTO comp_diodo_led (value) VALUES ('3 mm verde');
INSERT INTO comp_diodo_led (value) VALUES ('3 mm rojo');
INSERT INTO comp_diodo_led (value) VALUES ('3 mm azul');
INSERT INTO comp_diodo_led (value) VALUES ('3 mm violeta');
INSERT INTO comp_diodo_led (value) VALUES ('3 mm rosado');
INSERT INTO comp_diodo_led (value) VALUES ('3 mm maranjo');
INSERT INTO comp_diodo_led (value) VALUES ('3 mm amarilllo');
INSERT INTO comp_diodo_led (value) VALUES ('3 mm verde/amarillo');
INSERT INTO comp_diodo_led (value) VALUES ('3 mm blanco frio');
INSERT INTO comp_diodo_led (value) VALUES ('3 mm blanco cálido');
INSERT INTO comp_diodo_led (value) VALUES ('5 mm rojo');
INSERT INTO comp_diodo_led (value) VALUES ('5 mm azul');
INSERT INTO comp_diodo_led (value) VALUES ('5 mm ultra violeta');
INSERT INTO comp_diodo_led (value) VALUES ('5 mm 3 pin azul/verde');
INSERT INTO comp_diodo_led (value) VALUES ('5mm azul intermitente');
INSERT INTO comp_otros (value) VALUES ('puente rectificador');
INSERT INTO comp_otros (value) VALUES ('reles');
INSERT INTO comp_otros (value) VALUES ('potenciómetros');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 6x6x4mm.3 4pin');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 6x6x4.9mm 4pin');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 6x6x5.4mm 4pin');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 6x6x9mm 4pin');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 6x6x25mm 4pin');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 6x6x13,2mm 4pin');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 6x6x5.7mm 4pin');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 6x6x10mm 2pin');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 6x6x9mm 2pin');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 6x6x5mm 2pin');
INSERT INTO comp_otros (value) VALUES ('boton pulsador goma 7.8c7.8x5.4mm 2pin');
INSERT INTO comp_otros (value) VALUES ('Base IC 6 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 8 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 10 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 12 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 14 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 16 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 18 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 20 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 24 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 28 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 32 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 40 pin (DIP 300)');
INSERT INTO comp_otros (value) VALUES ('Base IC 24 pin (DIP 600)');
INSERT INTO comp_otros (value) VALUES ('Base IC 28 pin (DIP 600)');
INSERT INTO comp_otros (value) VALUES ('Base IC 32 pin (DIP 600)');
INSERT INTO comp_otros (value) VALUES ('Base IC 40 pin (DIP 600)');
INSERT INTO comp_otros (value) VALUES ('Base IC 48 pin (DIP 600)');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 12x12x4.3');
INSERT INTO comp_otros (value) VALUES ('boton pulsador 12x12x4.3 cuadrado');
INSERT INTO comp_otros (value) VALUES ('brocas cnc 0.7');
INSERT INTO comp_otros (value) VALUES ('brocas cnc 0.8');
INSERT INTO comp_otros (value) VALUES ('brocas cnc 0.9');
INSERT INTO comp_otros (value) VALUES ('brocas cnc 1.0');
INSERT INTO comp_otros (value) VALUES ('brocas cnc 1.1');
INSERT INTO comp_otros (value) VALUES ('brocas cnc 1.2');
INSERT INTO comp_otros (value) VALUES ('fresa 0.1 45°');
INSERT INTO comp_otros (value) VALUES ('jack dc 2.1mm');
INSERT INTO comp_otros (value) VALUES ('plug dc 2.1mm');
INSERT INTO comp_otros (value) VALUES ('jack 3.5mm audio');
INSERT INTO comp_otros (value) VALUES ('jack 6.3 mm audio');
INSERT INTO comp_otros (value) VALUES ('plug 3.5mm audio');
INSERT INTO comp_otros (value) VALUES ('plug 6.3mm audio');
INSERT INTO comp_otros (value) VALUES ('potenciómetros rotatorio mono');
INSERT INTO comp_otros (value) VALUES ('potenciómetros deslizante mono');
INSERT INTO comp_otros (value) VALUES ('encoder rotatorio');
INSERT INTO comp_otros (value) VALUES ('encoder rotatorio con boton');
INSERT INTO comp_otros (value) VALUES ('potenciómetros rotatorio estereo');
INSERT INTO comp_otros (value) VALUES ('potenciómetros deslizante estereo');
INSERT INTO comp_otros (value) VALUES ('llave selectora 4p3t');
INSERT INTO comp_otros (value) VALUES ('conector jst 2 pin');
INSERT INTO comp_otros (value) VALUES ('conector jst 3 pin');
INSERT INTO comp_otros (value) VALUES ('molex 2 pin');
INSERT INTO comp_otros (value) VALUES ('molex 3 pin');
INSERT INTO comp_otros (value) VALUES ('terminal block 2 pin');
INSERT INTO comp_otros (value) VALUES ('terminal block 3 pin');
INSERT INTO comp_otros (value) VALUES ('fusible 0.350mA');
INSERT INTO comp_otros (value) VALUES ('fusible 0.500mA');
INSERT INTO comp_otros (value) VALUES ('fusible 1a');
INSERT INTO comp_otros (value) VALUES ('fusible 3a');
INSERT INTO comp_otros (value) VALUES ('fusible 5a');
INSERT INTO comp_otros (value) VALUES ('trim pot varios valores');
INSERT INTO comp_otros (value) VALUES ('porta led 3mm');
INSERT INTO comp_otros (value) VALUES ('tuerca 3mm');
INSERT INTO comp_otros (value) VALUES ('tornillo 3mm');
INSERT INTO comp_otros (value) VALUES ('separador placa 3mm');
INSERT INTO comp_otros (value) VALUES ('spdt');
INSERT INTO comp_otros (value) VALUES ('dpdt');
INSERT INTO comp_otros (value) VALUES ('3pdt');
INSERT INTO comp_otros (value) VALUES ('4pdt');
INSERT INTO comp_otros (value) VALUES ('dip switch 2');
INSERT INTO comp_otros (value) VALUES ('dip switch 3');
INSERT INTO comp_otros (value) VALUES ('dip switch 4');
INSERT INTO comp_otros (value) VALUES ('dip switch 5');
INSERT INTO comp_otros (value) VALUES ('dip switch 6');
INSERT INTO comp_otros (value) VALUES ('dip switch 8');
INSERT INTO comp_otros (value) VALUES ('dip switch 10');
INSERT INTO comp_otros (value) VALUES ('cable awg 18');
INSERT INTO comp_otros (value) VALUES ('cable awg 20');
INSERT INTO comp_otros (value) VALUES ('cable awg 22');
INSERT INTO comp_otros (value) VALUES ('cable awg 24');
INSERT INTO comp_otros (value) VALUES ('cable awg 26');
INSERT INTO comp_otros (value) VALUES ('mini usb vertical');
INSERT INTO comp_otros (value) VALUES ('usb tipo B');
INSERT INTO comp_otros (value) VALUES ('display LCD 16x2');
INSERT INTO comp_otros (value) VALUES ('display 7 segmentos  1 digito');
INSERT INTO comp_otros (value) VALUES ('display 7 segmentos  2 digitos');
INSERT INTO comp_otros (value) VALUES ('display 7 segmentos  4 digitos');
INSERT INTO comp_otros (value) VALUES ('oled 2.4 pulgadas');